# Generated by Django 4.2.7 on 2025-11-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_counselorprofile_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselorprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='counselorprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='counselorprofile',
            name='consultation_methods',
        ),
        migrations.RemoveField(
            model_name='counselorprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='counselorprofile',
            name='total_sessions',
        ),
        migrations.RemoveField(
            model_name='counselorprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='career_readiness_score',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='dominant_skills',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='personality_type',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='years_experience',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
